# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 564013d6e10b08ecb9482518526939b82c60ef550055646fd4d8f03be6298b0bac1f92f97deb8bcb2425eefff3147f52b83c22eff57f1a969f88096bfbd1da0e

test:
  secret_key_base: 01d755bc47cf509853fd6fa361a34a9f1ad65346cd61c5d47522960d2135de1727e50d52a99873bb34e1fa4aa98a75be21f0a71685bfc35d7788877786ed2aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
